sheepdog/sheepdog

configure.ac, sheep/Makefile.am
allow to build with corosync 2.x
=> fix corosync depends

lib/Makefile.am, lib/shared/internal.h, lib/shared/ops.c, lib/shared/sheep.c, lib/shared/sheepdog.h, lib/shared/vdi.c
merge shared lib features from sheepdog-ng
=> merge shared lib features from sheepdog-ng

sheep/cluster/local.c, sheep/http/kv.c
Signed-off-by: hongzhou zhang <zhang.hongzhou@hotmail.com>
=> sheep/http/kv.c: Garbage return value

lib/net.c
=> dog: allow to specify hostnames in dog commands

sheep/gateway.c
Current code for COW requests can call panic() because it uses
xzalloc() and xcalloc() for processing the requests. This commit lets
the code avoid use the functions and return SD_RES_NO_MEM because COW
is a very common and frequent request. It is better to return error
code to VMs than killing sheep.
Even if the memory allocations fail, it just causes object leaks. This
behavior is not changed from the existing strategy which calls
panic().
=> sheep: avoid panic in COW when sheep fails to allocate memory

sheep/sheep.c, sheep/sheep_priv.h
=> cleanup messages about missing features

sheep/group.c, sheep/ops.c
This branch will solve the problem reported in https://github.com/sheepdog/sheepdog/issues/164
Could you try it, @sirio81 ?
=> Fixes the issue 164

sheep/ops.c
=> sheep: disable locking in a correct manner if -l isn't passed

lib/Makefile.am, sheepdog.spec.in
Signed-off-by: hongzhou zhang <hongzhou.h.zhang@intel.com>
=> Fix rpmbuild failure

Makefile.am, sheepdog.spec.in, tools/Makefile.am
This PR includes a reverting commit and a small rpm fix.
No need to fix debian/* files.
=> Add zk_control to rpm/deb package

sheep/gateway.c
@mitake Please review this PR.
```
-----Original Commit Message-----
sheep: remove xmalloc(), xzalloc() and xvalloc() from gateway path
Some functions in sheep/gateway.c call xmalloc(), xzalloc() and xvalloc().
These x*alloc() will kill sheep when memory allocation is failed. So they
should not be called.
This removes x*alloc() from the functions in the gateway path and make
them return error to their callers instead of killing sheep when memory
allocation is failed.
This closes sheepdog/sheepdog#207.
Signed-off-by: Takashi Menjo <takashi.menjo+github@gmail.com>
```
=> sheep: remove xmalloc(), xzalloc() and xvalloc() from gateway path

sheep/xio_client.c, sheep/xio_server.c
=> xio: minor style fixes

lib/net.c
This fixes #224
Tested-by: FUKUDA Yasuhito <fukuda.yasuhito@po.ntts.co.jp>
Signed-off-by: YAMADA Hideki <yamada.hideki@lab.ntt.co.jp>
=> Fix a overflow in str_to_addr

.gitignore, tests/unit/sheep/Makefile.am, tests/unit/sheep/mock_group.c, tests/unit/sheep/mock_request.c, tests/unit/sheep/mock_store.c, tests/unit/sheep/mock_vdi.c, tests/unit/sheep/test_cluster_driver.c, tests/unit/sheep/test_vdi.c
=> tests/unit: Fix unit tests to be built and passed

tests/unit/lib/Makefile.am, tests/unit/lib/test_work.c
Add unit tests for init_work_queue(), create_work_queue(), queue_work()
=> tests/unit: Add unit tests for lib/work.c

dog/vdi.c
Fix #246
Signed-off-by: Tbabm <liuzxzju@gmail.com>
=> dog: Output data_vdi_id in hex format in dump-inode

doc/option_-F_avoiding_diskfull_caused_by_recovery_process.txt
doc: add documentation of new option: -F avoiding diskfull caused by recovery process
Fixes https://github.com/sheepdog/sheepdog/issues/238
Signed-off-by: Seiji Matsumura <matsumura.seiji@lab.ntt.co.jp>
=> doc: add documentation of new option: -F avoiding diskfull caused by recovery process

tests/functional/041.out
It seems that this test was affected by 21af4810a4c5057621415c9928e5aa38e86142dc.
=> tests/functional: Fix functional test 041 to be passed

tests/functional/048.out
It seems that this test was affected by fe5d3ba71bbcfb8e0aedc0b6d261db1a4daa0043.
=> tests/functional: Fix functional test 048 to be passed

tests/functional/069, tests/functional/069.out
It seems that this test was affected by 162a732a15b8b5b0e327f8412e7f7f8335d32bd0.
=> tests/functional: Fix functional test 069 to be passed

tests/functional/073.out
=> tests/functional: Fix functional test 073 to be passed

tests/functional/088, tests/functional/088.out
Scenario of this test needs to change.
becouse, remove directory before "3. start sheep with my address again".
=> tests/functional: Fix functional test 088 to be passed

tests/functional/096.out
=> tests/functional: Fix functional test 096 to be passed

tests/functional/097, tests/functional/097.out, tests/functional/common.config, tests/functional/common.filter, tests/functional/common.rc
scenario of this test needs to change with the current situation.
=> tests/functional: Fix functional test 097 to be passed

tests/functional/101.out
The out file of this test is incorrect in the current code.
=> tests/functional: Fix functional test 101 to be passed

tests/functional/053
This test was affected by issue https://github.com/sheepdog/sheepdog/issues/103
=> tests/functional: Fix functional test 053 to be skiped

tests/functional/099.out
=> tests/functional: Fix functional test 099 to be passed

tests/unit/sheep/Makefile.am, tests/unit/sheep/test_group.c
Add unit tests for sd_accept_handler()
=> tests/unit: Add unit tests for sheep/group.c

tests/unit/sheep/Makefile.am, tests/unit/sheep/test_recovery.c
Add unit tests for start_recovery()
=> tests/unit: Add unit tests for sheep/recovery.c

sheep/store/common.c
=> sheep: turn on O_DIRECT just for data objects

.travis.yml, tests/functional/056, tests/functional/HOWTO, tests/functional/group, tests/script/README.md, tests/script/exec_functional, tests/script/exec_operation, tests/script/exec_unit, tests/script/prepare_for_test, tests/unit/README.md, tests/unit/sheep/test_hash.c, tests/unit/sheep/test_vdi.c
In addition, some tests have been modified.
=> tests: Create an environment for auto-testing with CI

tests/functional/109
=> tests: Make functional 109 more stable

tests/functional/111, tests/functional/111.out
=> tests: Add more tests to functional 111

sheep/sheep.c
=> sheep: create correct work queues

sheep/gateway.c
The async ledger update can cause data loss because the process of
decrementing reference count can be delayed and the target VID can be
used for newly created VDIs. This commit forbids the async update if
the cluster is formatted with VID recycling mode.
Fixes https://github.com/sheepdog/sheepdog/issues/315
=> sheep: disable async ledger update for VID recycling mode

doc/how_to_upload_packages.rst
Some procedures about making rpm have been added.
Signed-off-by: Seiji Matsumura <matsumura.seiji@lab.ntt.co.jp>
=> doc: "how_to_upload_packages.rst" has been modified.

configure.ac
=> Fix make error in case of './configure --enable-trace'

dog/vdi.c
=> new options for controlling requests during VDI deletion

lib/shared/ops.c
Fix https://github.com/sheepdog/sheepdog/issues/381
=> lib: fix a typo

dog/vdi.c
Reclamation of objects is a heavy operation and it needs careful
control. The new option -m can be used for stopping reclamation if
objects of a specified number are reclaimed.
=> dog: a new option -m for specifying the maximum number of reclamation

sheep/sheep.c
Hi,
I want to know in a very simple way how `sheep` binary was compiled with what kind of features.
So I tried to give that function to the `-v` option. What do you think of this?
---
This change provides displays supported cluster drivers and features in `-v` option.
e.g.
```
Sheepdog daemon version 1.0_126_g929d401_dirty
Supported features:
Cluster drivers: zookeeper corosync local
Miscellaneous: http diskvnodes nfs trace
```
Similarly, if the cluster driver option is wrong it will also display the supported cluster drivers. this is continue to avail.
e.g.
```
Invalid cluster driver 'hoge'
Supported features:
Cluster drivers: zookeeper corosync local
```
=> sheep: display features in the "-v" option.

sheep/gateway.c
Signed-off-by: hongtong.liu <hongtong.liu@istuary.com>
=> sheep/gateway: fix memory leak
