sheepdog/sheepdog

script/sheepdog.in

Source init-functions on deb-based distros to provide killproc.
Use SHEEPDOGD variable in init script
SHEEPDOGD is defined but is not used when starting sheep. This change
allows system default configs to override SHEEPDOGD if desired.
Use SHEEPDOG_PATH in init script
The debian defaults file has a comment that this environment variable
is used by the init script to set the sheepdog storage dir, however
the code in the init script does not support this claim. This change
makes the needed changes that allow this to work.

Various init script fixups

---

lib/shared/vdi.c

when porting shared lib patches from sheepdog-ng sd_vdi_rollback miss return code.

shared lib: fix rollback return code

---

dog/Makefile.am

dog binary may be used under non root user, so move it to proper place

dog: move dog binary to bin dir instead of sbin

---

sheep/cluster/local.c

Fix warning introduced by recent PR:
cluster/local.c: In function 'add_event':
cluster/local.c:310:3: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
if (n = xlfind(lnode, ev.lnodes, ev.nr_lnodes, lnode_cmp))
^
cluster/local.c:317:3: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
if (n = xlfind(lnode, ev.lnodes, ev.nr_lnodes, lnode_cmp))
^

Fix warning, add parentheses around assignment used as truth value

---

include/fec.h

This commit removes build warnings like below:
CC       net.o
In file included from ../include/internal_proto.h:25:0,
from ../include/sheep.h:16,
from net.c:31:
../include/fec.h: In function ‘ec_encode’:
../include/fec.h:175:6: warning: variable ‘pidx’ set but not used [-Wunused-but-set-variable]
int pidx[p];

isa-l: remove build warning

---

lib/isa-l/erasure_code/ec_multibinary.asm

Remove warning erasure_code/ec_multibinary.asm:255: warning: redefining multi-line macro `slversion'
Signed-off-by: hongzhou zhang <hongzhou.h.zhang@intel.com>

Remove warning erasure_code/ec_multibinary.asm:255

---

MAINTAINERS

MAINTAINERS: add hongzhou zhang as a subsystem maintainer of isa-l

---

configure.ac

Add configure failure to notice users to upgrade yasm to 1.2.0 or higher for x86_64 platforms.
AVX2 instructions are supported by yasm 1.2.0 since October 31, 2011.
Signed-off-by: hongzhou zhang <hongzhou.h.zhang@intel.com>

Add configure failure to notice users to upgrade yasm to 1.2.0 or higher

---

configure.ac
include/fec.h
lib/Makefile.am
lib/fec.c

This is to guarantee sheepdog can be installed on all x86_64 machines or with old OS.
Signed-off-by: hongzhou zhang <hongzhou.h.zhang@intel.com>

Disable ISA-L if Yasm 1.2.0 or higher is not supported.

---

dog/dog.h
dog/node.c
include/internal_proto.h
include/sheep.h
sheep/config.c
sheep/group.c
sheep/ops.c
sheep/sheep.c
sheep/sheep_priv.h
sheep/store/common.c

This PR is for rolling updating store format. For example, a cluster which starts with plain store can change its store to tree gradually.

decouple node format from cluster format for rolling update

---

sheep/request.c

When log admin ops in rx_main, it should use req->rq.data_length
rather than req->rp.data_length. If not, we will always get "not
string" because of req->rp.data_length equals zero.
Signed-off-by: Meng Lingkun <menglingkun@cmss.chinamobile.com>

sheep/request: fix bug of inconsistency between data_length and data

---

sheep/ops.c

For the third-party management systems (cinder, etc), they always
record the volume names rather than vid. If the volume is not
deleted, We can get vid from volume name by dog vdi list. However,
if the volume was deleted for some reason, the administrator can't
get vid from volume name when he traces when and what happened to
the volume. Thus, adding volume name and sender information for
creating and deleting is helpful. Sender can guide administrators
to the sender node for detailed information.
Signed-off-by: Meng Lingkun <menglingkun@cmss.chinamobile.com>

sheep: add more info log for creating and deleting a volume

---

tests/unit/mock/mock.h

If not includes util.h, the macro of LOCAL can't be handled, which
will result in compilation fails.
Signed-off-by: Meng Lingkun <menglingkun@cmss.chinamobile.com>

sheep/test: include util.h for LOCAL when configure --enable-unittest

---

tests/functional/common.config
tests/functional/common.rc

As explained in commit 89f6b6a86ff50fe14a6c95b736a346f601d6418c, pgrep
has a destructive update. For sheep, it's better to support the two
different versions. This patch just does this in a simple and maybe
silly way.
Signed-off-by: Meng Lingkun <menglingkun@cmss.chinamobile.com>

tests/functional: adapt to destructive update of pgrep

---

sheep/group.c

If a cluster isn't formatted with -l option, creating a checkpoint of
vdi state if it isn't necessary.

sheep: avoid creating a checkpoint of vdi state if it isn't necessary

---

dog/vdi.c
include/internal_proto.h
lib/shared/vdi.c
sheep/group.c
sheep/ops.c
sheep/request.c
sheep/sheep_priv.h

The mechanism of inode update prevention mechanism was introduced in
the commit 449331b4d0c. The original motivation of this mechanism was
for reducing object leak which can happen during taking
snapshot. However, the object leak problem seems to be solved in the
qemu side commit 20760b16b73. I've been kept the mechanism because it
was useful for hiding incomplete state of VDIs (snapshot is created
but new working VDI isn't created yet) from clients. For simplifing
the design of sheepdog, the problem should be handled in the clients.
The retrying mechanism in the qemu driver is already ongoing:
https://github.com/sheepdog/qemu/tree/reconnect-and-reload

remove inode update prevention

---

sbd/sheep_block_device.c

strict_strtoul() was just a redefinition of kstrtoul() for a long
time. From kernel version of 3.18, strict_strtoul() will not be
defined at all. A compile time kernel version check is needed to
decide which function or macro can be used for a specific version of
kernel.

fix strict_strtoul for never kernels

---

sheep/ops.c

sheep: do nothing in cluster_lock_vdi_work() if vdi locking is disabled

---

tests/functional/common.rc

When cleaning up devices, search in sub-directories of /dev/
is not necessary
Signed-off-by: Ruoyu <liangry@ucweb.com>

tests: limit search in sub-directories of /dev

---

lib/util.c

On error, -1 is returned and errno is set to indicate the error.
Signed-off-by: Yu Yang <yuyang@cmss.chinamobile.com>

lib/util: fix bug for return value check of readlink()

---

debian/sheepdog.bash-completion

When you install sheepdog via deb package, you will find following error.
This patch delete a unnecessary file.
$ ssh -A ubuntu@10.36.2.55
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.16.0-51-generic x86_64)
* Documentation:  https://help.ubuntu.com/
Last login: Fri Oct 23 15:30:02 2015 from dhcpfe82.osrg.net
-bash: script/bash_completion_dog: No such file or directory
-bash: script/bash_completion_dog: No such file or directory
-bash: script/bash_completion_dog: No such file or directory
-bash: script/bash_completion_dog: No such file or directory
Signed-off-by: YAMADA Hideki <yamada.hideki@gmail.com>

Fix bash-completion error when using deb package

---

configure.ac
include/internal_proto.h
include/net.h
include/xio.h
lib/Makefile.am
lib/sockfd_cache.c
lib/xio.c
sheep/Makefile.am
sheep/gateway.c
sheep/request.c
sheep/sheep.c
sheep/sheep_priv.h
sheep/xio.c
shepherd/Makefile.am

This patch adds a support of accelio, an library of RPC which wraps
TCP and RDMA in clean way, to sheepdog. With this change, sheepdog
will be able to utilize high speed interconnect like infiniband.
The code is very early stage and have bunch of ToDos. However, I'd
like to share it and want the community to help the implementation.
How to build:
1. install accelio
2. ./configure --enable-accelio
3. make
How to use:
$ sheep -i transport=rdma,host=xxx,port=yyy ...
Minor ToDos:
- clean up code (e.g. comment out)
- remove known segfault bugs
- sane error handling
- remove memory leaks
- vdi creation with preallocation fails
Major ToDos:
- enhance code for utilizing RDMA
- rx/tx in worker threads (I'm not sure it is effective because RDMA
helps to reduce CPU consumption)
Signed-off-by: …

initial accelio support

---

tests/unit/dog/Makefile.am
tests/unit/sheep/Makefile.am

Common versions of automake have a bug[1] related to enabling
subdir-objects while using variables inside *_SOURCES declarations.
In order to work around these problems with the unit tests, copy
source dependencies locally for building, using GNU make patterns.
[1] http://debbugs.gnu.org/cgi/bugreport.cgi?bug=13928
Signed-off-by: Alexander Guy <alexander@andern.org>
Signed-off-by: Liu Yuan <liuyuan@cmss.chinamobile.com>
Signed-off-by: YAMADA Hideki <yamada.hideki@gmail.com>

automake: work-around for not expanding variables in _SOURCES.

---

Makefile.am

We don't need zookeeper as runtime dependency, because it can run
on other server.
And we should use Apache Bigtop's zookeeper library package which
are recommended in following JIRA.
The package name is not 'zookeeper-lib-devel'.
It is 'zookeeper-native'.
JIRA:
- https://issues.apache.org/jira/browse/ZOOKEEPER-1604
- https://issues.apache.org/jira/browse/ZOOKEEPER-2275
Apache Bigtop Website:
- http://bigtop.apache.org/
Apache Bigtop Repository:
- http://www.apache.org/dist/bigtop/bigtop-1.0.0/repos/centos7/bigtop.repo
Signed-off-by: YAMADA Hideki <yamada.hideki@gmail.com>

rpm: fix zookeeper dependencies

---

include/util.h
lib/util.c

@mitake Would you review this PR?
```
-----Original Commit Message-----
lib/util: remove try_to_free_routine()
Several memory-allocation functions in lib/util.c call
try_to_free_routine(). The routine is a function pointer. It is initialized
as do_nothing and can be set by set_try_to_free_routine(). However, no one
calls set_try_to_free_routine() in fact. So these code really do nothing.
This removes try_to_free_routine() and related lines.
This closes sheepdog/sheepdog#210.
Signed-off-by: Takashi Menjo <takashi.menjo+github@gmail.com>
`````

lib/util: remove try_to_free_routine()

---

dog/Makefile.am
dog/benchmark.c
dog/dog.c
dog/dog.h

This commit adds a new command "benchmark" for easy benchmarking. It
will make performance evaluation easier (e.g. I/O performance,
multicore scalability).

dog: a new command for benchmarking

---

sheep/store/md.c

Please review this PR. This closes sheepdog/sheepdog#214.
```
-----Original Commit Message-----
After the last object store removed or unplugged from a sheep,
it still runs as a member of cluster with no object store.
In such cases, it should go down i.e. leave cluster and die.
This closes sheepdog/sheepdog#214.
Signed-off-by: YAMADA Hideki <yamada.hideki@gmail.com>
Signed-off-by: Takashi Menjo <takashi.menjo+github@gmail.com>
```

md: go down when no object store becomes available or plugged

---

sheep/sheep.c

Please review this PR. This closes sheepdog/sheepdog#203.
```
-----ORIGINAL COMMIT MESSAGE-----
Without --enable-http configure option, we still get
-Wunused-but-set-variable warning message on 'http_options'
in the main function of sheep.
This not only fixes the warning, but also makes sheep not show
the help message about -r/--http option. Note that disabling
HTTP feature itself had been realized in commit 00965c1.
This closes sheepdog/sheepdog#203.
Signed-off-by: Takashi Menjo <takashi.menjo+github@gmail.com>
```

sheep: fix 'http_options' warning when building

---

sheep/vdi.c
tests/unit/sheep/Makefile.am
tests/unit/sheep/test_vdi.c

The function ```fill_vdi_state_list()``` implementing ```SD_OP_GET_VDI_COPIES``` should set the ```deleted``` member of ```struct vdi_state``` and respond it.
This is mainly for sheep/group.c:```get_vdis_from()``` because it set VDI bitmap ```sys->vdi_deleted``` based on the value of ```deleted``` member responded by ```SD_OP_GET_VDI_COPIES``` request.
I separate my work into 3 commits. First one refactors related unit tests to use Unity framework. Second one adds unit tests. Third one fixes ```fill_vdi_state_list()```.
Fixes #234.

sheep/vdi: Fix fill_vdi_state_list() to set 'deleted' member

---

dog/cluster.c
include/internal_proto.h
sheep/recovery.c

sheep can corrupt its cluster by diskfull with recovery process. For
avoiding this problem, this patch adds a new option -F to sheep. If
this command is passed to the sheep process, every sheep process of
the cluster stops itself if there is a possibility of diskfull during
recovery.
Fixes https://github.com/sheepdog/sheepdog/issues/59

sheep: avoid diskfull caused by recovery process

---

tests/operation/README.md
tests/operation/fixture.py
tests/operation/proto.py
tests/operation/sheep.py
tests/operation/test_3nodes_2copies.py
tests/operation/test_fixture.py

Sheepdog RPCs i.e. `SD_OP_*` cannot be tested easily with existing testing ways. Writing such tests as unit tests in C is boring. Functional tests are not so fine-grained as to make such tests.
This introduces "operation test" in tests/operation to test RPCs. It is written in Python, and contains two main modules:
1. sheep.py: providing Sheepdog RPCs
A basic RPC way like as executing `*_exec_req` is implemented. Wrapper methods are also implemented for some RPCs to handle their return values like as C struct.
2. fixture.py: providing testing fixtures
We can start sheep processes with temporary disks and run some dog commands with this.
Now we can make RPC tests using these modules and PyUnit framework, easier-to-write than unit test and finer-grained than functional test.
I think this is …

tests: Add operation test

---

sheep/vdi.c

This code increments the nr_participants but the participant state is not updated yet. The is_modified will now iterate over the updated nr_participants and can see bad state in participant_state array.
This PR increments participant counter after the participant state is updated.

Increment participant count after updating all state

---

include/common.h
lib/common.c
sheep/config.c
sheep/store/common.c
sheep/store/md.c
tests/unit/lib/Makefile.am
tests/unit/lib/test_atomic_create_and_write.c
tests/unit/lib/test_punchhole.c

This adds a parameter 'sparse' to atomic_create_and_write(). If sparse is true, atomic_create_and_write() should create sparse file. Otherwise, it should do like as before i.e. create non-sparse file.
This also makes md_move_object() in sheep/store/md.c call atomic_create_and_write() with sparse=true. Hereby, object files will be sparsed when they move between disks.
Fixes #227.

lib: A sparse file can be created with atomic_create_and_write()

---

dog/vdi.c
include/internal_proto.h
include/sheepdog_proto.h

This is the remaining work related to PR #226. This removes not only SD_OP_DELETE_CACHE but also SD_OP_FLUSH_VDI, so whole the command `dog vdi cache` also be removed.
We might want to close issues #64 and #74.

dog: Remove object cache feature

---

lib/common.c

Met below error on centos
common.c: In function ‘atomic_create_and_write’:
common.c:78:9: error: ‘FALLOC_FL_KEEP_SIZE’ undeclared (first use in this function)
fd, FALLOC_FL_KEEP_SIZE | FALLOC_FL_PUNCH_HOLE,
^
common.c:78:9: note: each undeclared identifier is reported only once for each function it appears in
common.c:78:31: error: ‘FALLOC_FL_PUNCH_HOLE’ undeclared (first use in this function)
fd, FALLOC_FL_KEEP_SIZE | FALLOC_FL_PUNCH_HOLE,
^
make[1]: *** [common.o] Error 1
Signed-off-by: Frank Yu <flyxiaoyu@gmail.com>

lib: fix the build error on centos

---

lib/common.c
sheep/store/common.c
tests/unit/lib/test_punchhole.c

Signed-off-by: Frank Yu <flyxiaoyu@gmail.com>

use the appropriate headers instead of define the macros

---

tests/functional/055

Scenario of this test needs to change in the current code.
The sheep process is down when the dir of metadata-store deleted.

tests/functional: Fix functional test 055 to be passed

---

tests/functional/081
tests/functional/081.out

tests/functional: Fix functional test 081 to be passed

---

tests/functional/082
tests/functional/082.out

tests/functional: Fix functional test 082 to be passed

---

tests/functional/084

tests/functional: Fix functional test 084 to be passed

---

tests/functional/087
tests/functional/087.out

tests/functional: Fix functional test 087 to be passed

---

tests/functional/089
tests/functional/089.out

tests/functional: Fix functional test 089 to be passed

---

tests/functional/090
tests/functional/090.out

tests/functional: Fix functional test 090 to be passed

---

tests/functional/095

loopback device is not required by this test.
becouse, change loopback device to directory.

tests/functional: Fix functional test 095 to be passed

---

tests/functional/100.out

It seems that this test was affected by 5c14171d7f9e4824c603c19ba3705b826bdb613c.

tests/functional: Fix functional test 100 to be passed

---

dog/node.c

This commit replaces strtoul/strtoull (pay attention to &quot;u&quot;) with strtol/strtoll (no &quot;u&quot;) to check negative values right.
Passing negative values to &quot;dog node recovery set-throttle,&quot; I got below. The case -1 is as I expected, but the case -2 is not:
$ dog node recovery get-throttle
max(0), interval (0)
$ dog node recovery set-throttle -- -1 -1
Invalid max (-1)
$ dog node recovery get-throttle
max (0), interval (0)
$ dog node recovery set-throttle -- -2 -2
$ dog node recovery get-throttle
max (4294967294), interval (18446744073709551614)
This is because of strtoul/strtoull. These functions accept a string beginning with minus sign then, if non-negated value does not overflow, return the conversion represented as an unsigned value without error. So I got …

dog: Make "dog node recovery set-throttle" reject negative values

---

include/util.h
lib/util.c
sheep/sheep.c
tests/functional/108
tests/functional/108.out
tests/functional/109
tests/functional/109.out
tests/functional/110
tests/functional/110.out
tests/functional/group
tests/unit/lib/test_util.c

This PR adds two functions str_to_u32 and str_to_u16 to lib/util.c. These functions convert a string into a 64-bit integer with strtoll. Then they check whether a converted value is in the valid range or not and, if something goes wrong because of an empty string, an invalid character, a negative value or overflow, sets errno accordingly.
Using them, this enforces strict range validation of -p/--port, -z/--zone and -V/--vnodes.
This also adds some unit and functional tests to verify the change.
Fixes #296

sheep: Validate -p/--port, -z/--zone and -V/--vnodes values strictly

---

dog/node.c
tests/functional/111
tests/functional/111.out
tests/functional/group

This PR enforces strict range validation of `dog node vnodes set` like as the commit c19170a in PR #297.
This also add a functional test 111 for regression testing.

dog: Validate "dog node vnodes set" value strictly

---

tests/functional/112
tests/functional/112.out
tests/functional/113
tests/functional/113.out
tests/functional/group

This PR adds two functional tests for regression testing. The 112 checks join, leave, format and shutdown. The 113 checks reweight, and step-by-step join and leave.
This is test-only PR. I'll merge it if Travis CI has passed.

tests: Add functional tests 112 and 113 to test fixed vnodes feature

---

sheep/vdi.c

This is for iSCSI multipath usage with tgtd.
When sheep receives SD_READ_OBJ request from tgtd, the function is_refresh_required is called. When it returns true, the tgtd reloads the inode object of the target VDI.
In the current sheep implementation, is_refresh_required returns false if the target VDI is snapshot. This lets tgtd not reload the inode object then leads to inode inconsistency between tgtd when all of the following conditions are met:
* iSCSI multipath is configured (1-active and N-standby)
* a non-snapshot VDI is set as a new LUN of tgtd
* a snapshot of the VDI above is taken
* active path switched after the snapshot is taken
* tgtd sends SD_READ_OBJ after the active path switched
Also, the function validate_myself has a similar issue.
This PR fixed the problems described …

sheep: Check shared lock state even if VDI is snapshot

---

dog/vdi.c
tests/functional/097.out

Previously, `dog vdi lock list` outputs only VDIs' name and owner node(s). However, this is not enough because not only working VDIs but also snapshot ones can be locked.
This commit adds VDIs' snapid, id and tag columns to output of `dog vdi lock list`, like `dog vdi list`. After this, its output is like below:
```
Name         Id  VDI id  Tag            Owner node(s)
s foovdi        1  270cf4  foo1           [..]
foovdi        0  270cf5                 [..]
c hoge          0  8c7d08                 [..]
```
Note that raw output mode is not supported yet.
Fix #126.

dog: Refine output of "dog vdi lock list"

---

script/sheepdog.service.in

SystemD doesn't listen to anyone's ulimit methods. It forces the daemon and it's children to 1024. There is a complex way of allocating more resources to a 'slice' using additional SystemD files but I've found that "LimitNOFILE" works as well after a reboot of the entire system, not just a daemon-reload or service restart.
Also, when Sheepdog 'crashes', the signal doesn't propagate through /bin/sh (the method to which you are starting Sheepdog) so SystemD only 'sees' a non-zero exit code. On-abort only handles unclean signals, on-failure handles both signals and exit codes. This restarts the sheepdog daemon automatically if it 'fails'.

SystemD doesn't listen to ulimit

---

dog/vdi.c

This PR adds `-s/--snapshot` option to `dog vdi lock unlock` that enables users to unlock not only working VDI but also snapshot VDI.
This PR also fixes error check of `dog vdi lock list`.

dog: Support snapshot unlock with "dog vdi lock unlock"

---

lib/util.c

The present xrealloc panics as &quot;Out of memory&quot; if realloc returns NULL. However, man page of realloc[1] says that &quot;If size was equal to 0, either NULL or a pointer suitable to be passed to free() is returned.&quot; So xrealloc can panic wrongly when size is equal to 0 and realloc returns NULL.
This commit fixes the issue described above. The man page also says that &quot;The UNIX 98 standard requires [..] realloc() to set errno to ENOMEM upon failure.&quot; So I evaluate errno instead of returned value to check whether out of memory really occurred or not.
[1] http://linux.die.net/man/3/realloc

lib/util: Fix xrealloc to check out of memory error correctly

---

sheep/object_list_cache.c

When a sheep receives SD_OP_GET_OBJ_LIST request, xrealloc is called to allocate memory for object list which is being sent to the requesting. However, xrealloc panics if out-of-memory (OOM) error occurs. In this case, the sheep goes down. This is not good for stable running.
This commit lets sheep handle OOM error gracefully when it receives SD_OP_GET_OBJ_LIST. If OOM error occurs, sheep returns SD_RES_NO_MEM. This is realized by using realloc instead of xrealloc (note &quot;x&quot;) and check whether errno is set to ENOMEM or not.
See also #312.

sheep: handle OOM error gracefully when receive SD_OP_GET_OBJ_LIST

---

Makefile.am
tests/unit/dog/Makefile.am
tests/unit/lib/Makefile.am
tests/unit/sheep/Makefile.am

There are *.info files under submodules. They are not for coverage report but deleted by 'make clean'. This PR fixes the issue above.
This PR also renames coverage report file for lib to 'lib.info'. That should not be 'sheep.info'.
Fix #324.

tests: clean *.info files individually to avoid making submodules dirty

---

tests/unit/lib/Makefile.am
tests/unit/sheep/Makefile.am

Due to double-clean .deps directory, 'make disctlean' was failed. To avoid the issue above, this commit lets 'make' copy nessesary *.c files under each unit test directory. This also lets 'make distclean' delete that files.
Fix #326.

tests: fix 'make distclean' error

---

sheep/ops.c

Each object list cache should be removed when it is removed from object store. Inode and data ones are done so by peer_remove_obj. However, ledger objects are not so by peer_decref_object, and remaining cache leads to unnecessary recovery trial and error log.
This commit lets sheep remove object list cache of ledger when it is removed from store.
Fix #341

sheep: remove object list cache of ledger when removed from store

---

tools/zk_control.c

Now zk_control purge ...
* can purge znodes created within last 24 hours
* purges znode created before more than 24 hours by default i.e. when threshold is not given explicitly
* returns error when threshold is negative value (bug fix)

zk_control: fix "purge" threshold and default behavior

---

tests/functional/108

Sleeping 1 second after starting sheep process is too short. This commit let the test sleep 5 seconds at most.

test: fix flaky functional 108

---

tools/zk_control.c

Current zk_control implementaion don't show a resulted number of deleted nodes when purge is failed.
This patch is to show a resulted deleted number of nodes on stderr.
Signed-off-by: Hiroshi Miura <miurahr@linux.com>

zk_control: Log exact number of deleted nodes when purge is failed

---

dog/benchmark.c
include/work.h
lib/work.c
sheep/sheep.c
tests/unit/lib/test_work.c
tests/unit/sheep/test_recovery.c

This patch deletes WQ_UNLIMITED option because, with this option, sheep may consume a very large amount of memory (in some cases, to be killed by OOM-killer) by creating worker threads infinitely.
This patch also changes the upper limit for the number of threads for WQ_DYNAMIC option from "#nodes*2" to "max(#nodes,#cores,16)*2".
Signed-off-by: Teruaki Ishizaki &lt;ishizaki.teruaki@lab.ntt.co.jp&gt;

Remove WQ_UNLIMITED and change the limit of threads for WQ_DYNAMIC

---

include/work.h
lib/work.c
sheep/sheep.c

This PR adds a new option **-x** to sheep for configuring the maximum number of threads for dynamic workqueues.
Example:
```
$ sheep -x 500
```
If this is not passed, sheep uses a default formula for configuring the maximum number (that is, *max(#nodes,#cores,16)\*2*).
This is for tuning performance, so please be careful to use. Sheep works very slowly if you give a too small number, or may be shot by OOM-killer under heavy load if you give a huge number.
-----
This also makes a minor change on "doubling growth". If the double of the current number of threads for a dynamic queue exceeds the maximum number, that workqueue grows into that maximum number.
-----

sheep: add a new option for setting threads for dynamic workqueues

---

dog/benchmark.c
dog/common.c
dog/farm/farm.c
dog/farm/object_tree.c
dog/vdi.c
lib/sd_inode.c
sheep/gateway.c
sheep/group.c
sheep/http/kv.c
sheep/http/oalloc.c
sheep/nfs/fs.c
sheep/nfs/nfs.c
sheep/object_list_cache.c
sheep/ops.c
sheep/recovery.c
sheep/request.c
sheep/store/common.c
sheep/store/plain_store.c
sheep/store/tree_store.c
sheep/vdi.c
sheepfs/volume.c
tests/functional/028.out
tests/functional/042.out
tests/functional/080.out

This commit lets Sheepdog print object ID in 16-digit zero-padded hexadecimal, that is, `"%016" PRIx64`.
I think this is operator-friendly because s/he can tell whether that object is a data object (00...), an inode object (80...), a ledger object (08...) and so on, simply by looking at the printed.
Fix #340

Print object ID in '"%016" PRIx64'

---

sheepdog.spec.in

In the current spec.in, rpmbuild fails in sysvinit distribution(ex: el6).
Therefore, set behavior in the case of systemd, and explicitly divide it
from sysvinit behavior.

rpm: support for systemd and sysvinit

---

CHANGELOG.md
configure.ac
dog/common.c
dog/farm/farm.c
dog/farm/object_tree.c
dog/vdi.c
include/util.h
include/work.h
lib/sd_inode.c
lib/util.c
lib/work.c
sheep/gateway.c
sheep/http/kv.c
sheep/http/oalloc.c
sheep/nfs/fs.c
sheep/nfs/nfs.c
sheep/object_list_cache.c
sheep/ops.c
sheep/recovery.c
sheep/request.c
sheep/sheep.c
sheep/store/common.c
sheep/store/plain_store.c
sheep/store/tree_store.c
sheep/vdi.c
sheepdog.spec.in
sheepfs/volume.c
tests/functional/028.out
tests/functional/042.out
tests/functional/080.out

**Please DO NOT merge this PR.** This is only for review.
See also #354.
IMPORTANT CHANGES:
- Unlimited workqueue is now removed and changed to dynamic one. This is for sheep not to consume a huge amount of memory by creating new threads infinitely under heavy load, and to avoid being shot by OOM-killer.
- zk\_control now can purge znodes within 24 hours. It purges znodes created before the given threshold. This is useful if tens of thousands of znodes are created in a day.
SHEEP COMMAND INTERFACE:
- New option "-x" to set the maximum number of threads for dynamic workqueue. (default: decided by "max(#nodes,#cores,16)\*2" formula)
ZK\_CONTROL COMMAND INTERFACE:
- The "purge" subcommand can take a non-negative interger as a threshold in seconds. (default: 86400 (24 hours))
LOGGING:
- Print …

sheepdog stable release v0.9.5_rc0

---

script/dump_config.py

This make it easy to look into a "config" file. Please give this script your "config" file via standard input.
```
ctime            2017-02-15T06:43:18.019280+00:00 (0x58A3F88601263080)
flags            AUTO_VNODES (0x0004)
copies           3
default_store    plain
shutdown         True (1)
copy_policy      replica (0x00)
block_size_shift 22
version          6
space            10.0 GiB (10693148672)
```
```
ctime            2017-02-15T06:44:08.659537+00:00 (0x58A3F8B8274FBC68)
flags            RECYCLE_VID|AVOID_DISKFULL (0x0030)
copies           3
default_store    tree
shutdown         True (1)
copy_policy      ec#2:1 (0x11)
block_size_shift 23
version          6
space            10.0 GiB (10693148672)
```

script: add dump_config.py for debugging

---

include/sheepdog_proto.h
sheep/gateway.c
sheep/request.c
sheep/sheep.c
sheep/sheep_priv.h
sheep/store/common.c

Current sheepdog uses the io workqueue (sys->io_wqueue) for 2 kinds of
requests: peer and local. However, this architecture can cause
deadlock in the fixed workqueue mode because of the schedules like
below:
1. node A receives a request Ra from a client, queue Ra to io_wqueue
as a peer request
2. node B receives a request Rb from another client, queue Rb to
io_wqueue as a peer request
3. in node A, Ra forwards the requests to node B
4. in node B, Rb forwards the requests to node A
5. if node A or node B don't have idle workers in io_workqueue, it can
cause deadlock
This commit avoids the problem by creating a new dedicated workqueue
sys->peer_wqueue for avoiding the problem.
/cc @tmenjo it would be a serious problem, could you …

sheep: create a dedicated workqueue for peer requests

---

CHANGELOG.md
configure.ac
sheep/gateway.c

**Please do not merge this PR yet.**
@mitake May I have a request for your comments?
-----
As mentioned in #362, there is a risk of deadlock in the stable-0.9 branch. We can mitigate (or may remove) the risk by increasing the maximum number of threads for workqueues enough. However, it is hard to forecast the behavior of parallel execution of (1) and (2) below, making it difficult to estimate the number of threads:
* (1) gateway_write_object (run in a "gateway" thread) to update the data_vdi_id field of an inode, causing update of reference count
* (2) async_update_obj_refcnt_work (run in an "io" thread) to update reference count, following 1)
This commit lets the two above run in serial in a "gateway" thread. Note that the (2) is now update_obj_refcnt.
This reverts commit …

[stable-0.9] Revert "sheep: update ledger objects in an asynchronous manner"

---

sheep/gateway.c
sheep/sheep_priv.h
sheep/store/common.c

This PR ...
* rewrites duplicated code in gateway_handle_cow() with sd_{read,write}_object_fwd.
* removes sd_discard_object() because no one calls it.

sheep: clean-up duplicated or unused code

---

tests/unit/lib/Makefile.am
tests/unit/sheep/Makefile.am

The "make dist" (and other targets depending on it such as "make rpm") has tried to put cmock.c and unity.c in dist but failed in a case of not fetching submodules.
This commit removes them two files from dist by "nodist_" prefix.

Fix "make dist" error related to cmock.c and unity.c

---

Makefile.am
sheepdog.spec.in

Hi,
This PR solves some minor problem of spec.
The current speepdog.spec created with `make rpm` is incomplete.
This is because it has undefined macros. (that were supposed to be added from Makefile.)
e.g. `%{_have_zookeeper}`, `%{_configopts}` ...
Using undefined macros will fail with `rpmlint` test. and it makes difficult to rebuild from srpm.
Give the default values to undefined macros. and Makefile manages only flags of macros.
So real configure args will defined in the spec. it will in a changeable from flags.
The default value is `%{_have_zookeeper}` , `%{_have_fuse}` are both `0`. (well... it will be overwritten by in Makefile.)
by doing so, we can satisfy the specification of rpm spec.
The confirmation build env is [here](https://gist.github.com/kazuhisya/e36d36f12b2f5bacb14e23e60f …

rpm: give the default values to undefined macros.

---

configure.ac
sheepdog.spec.in

Corosync is a default cluster management backend, 
but it seems that the official recommended is zookeeper.
https://github.com/sheepdog/sheepdog/wiki/Cluster-Management-Backends-and-dual-NIC
We choose zookeeper, so don't want to be annoying about corosync dependency during build/install rpm.

rpm: build --disable-corosync

---

Makefile.am
sheepdog.spec.in

Sorry to bother you, this patch is complement to pull request #373.
This fix is also needed to build rpm without corosync.

rpm: fix handling corosync dependency

---

Makefile.am
script/gen_bash_completion.pl

This provides a really small fix.
- c7e9136: `.spec` file created by `make rpm` should have owner write permission.
- 70c9b9c: remove shebang from bash_completion.
---
Signed-off-by: Kazuhisa Hara <<khara@sios.com>>

script, Makefile: fix of permission and shebang

---

Makefile.am
script/gen_bash_completion.pl
sheepdog.spec.in

Hi,
This PR is related to issue #374. Can I get reviews and/or opinions?
I implemented `.rpm` subpackages as follows.
1. `sheepdog` : The Sheepdog Distributed Storage System for QEMU (main)
2. `sheepdog-libs` : Shared libraries for Sheepdog
3. `sheepdog-devel` : Header files for Sheepdog
4. `sheepdog-corosync` : Corosync cluster driver for Sheepdog
5. `sheepdog-zookeeper` : ZooKeeper cluster driver for Sheepdog
6. `sheepdog-sheepfs` : FUSE-based pseudo file system for Sheepdog
With this change, `configure` and `make` runs multiple times in `make rpm` depending on the options given. it may not be a little elegant...
How do you think?
(This PR is also include PR #376.)
The `.rpm` to be created is determined according to the `configure` options of `make rpm`.
| Condition                 | …

(refs#374) rpm: sub-package separation

---

script/Makefile.am
script/sheepdog.sysconfig
sheepdog.spec.in

Put the template in sysconfig. This make it easier maintaining sheepdog
service settings.

script: add a default template to sysconfig

---

sheepdog.spec.in

In order to compile `sheep` binary with corosync enabled,
`cpg.h` and `cfg.h` are required additionally.
https://github.com/sheepdog/sheepdog/blob/master/sheep/cluster/corosync.c#L14-L15

rpm: add rpm BuildRequires for corosync

---

script/checkpatch.pl

`checkpatch.pl` uses perl regex which do not escape curly braces. In Perl 5.22 or higher, unescaped left curly braces in a regex are deprecated and will outputted a warning. and this will be an error rather than a warning in future versions (maybe 5.26?).
This change provides suppress above problem.
See also: http://perldoc.perl.org/perl5220delta.html#New-Warnings
(`Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%s/` section)
Reproducible Env: fedora25
```
$ ./script/checkpatch.pl 0001-test.patch 
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\#\s*define.*do\s{ <-- HERE / at ./script/checkpatch.pl line 2163.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE …
```

script: fix "Unescaped left brace in regex is deprecated" warnings.

---

tests/functional/114
tests/script/exec_unit
tests/script/prepare_for_test

refs: #395
- 43f8125: tests/script/* : added support for testing with CentOS 7.x 
- This change provides support for the testing scripts with CentOS 7.x
- It has the following features:
- Modify the commands path depending on distributions
- Modify the package to be prepared depending on distributions
- Use qemu-io (is enabled sheepdog) prepared by [CentOS Virt-SIG](https://wiki.centos.org/SpecialInterestGroup/Virtualization)
- 340e421: tests/functional/114 : fix functional 114 to take into account the block of SELinux.
- If SELinux is not `disabled` (`enforcing` or `permissive`), functional test No.114 will fail.
- This is because, a single block for SELinux's attribute is added to the `%b * %B` of stat command output, so the output result is different from the SELinux disabled …

tests: added support for testing with CentOS 7.x

---

Makefile.am
sheepdog.spec.in

Makefile:
This change provides shepherd cluster daemon will only build
if it is explicitly enabled("--enable-shepherd").
rpm:
Now it can choose to install shepherd binary file synchronously
with configure options.

Makefile: shepherd is only build if it is explicitly enabled

---

sheep/sheep.c

This change provides displays lttng-ust feature in `-v` option.

sheep: add display lttng-ust feature in the '-v' option

---

sheep/Makefile.am

Fix syntax minor corruption of Makefile.
`nfs/nfs.h` (and `nfs/fs.h`) should be included in `noinst_HEADERS`.

sheep/Makefile: nfs/nfs.h should be included in noinst_HEADERS

---

Makefile.am
doc/how_to_upload_packages.rst
sheepdog.spec.in

9977d37: `rpm: add more configure options`
It can be dealt to more configure options when doing `make rpm`.
For example, the following configs are possible.
```console
$ ./autogen.sh
$ ./configure --enable-corosync --enable-zookeeper \
--enable-sheepfs --enable-shepherd --enable-http \
--enable-nfs --enable-diskvnodes --enable-lttng-ust \
--enable-trace
$ make rpm -j
```
precondition: #400
---
0e0aed7: `doc: modified how_to_upload_packages.rst`
It is no longer necessary to prepare rpm spec.
Currently `make rpm` is available.

rpm: add more configure options

---

Dockerfile
docker/cdog

Fix error '/usr/sbin/dog: no such file or directory' when running ./docker/cdog cluster format

Fix typos of docker in case of '/usr/sbin/dog not found'

---

sheep/store/md.c

Signed-off-by: Shien Xie <shien.xie@kaixiangtech.com>
The positions calculated by hash functions are not evenly spread on the ring. The situation will be worsen if the positions are hashed twice. For example, if the node has multiple disks and imbalance among disks is worse than imbalance among nodes.
The solution is to reduce the size of vdisk from 1G to 16M. The following is the result. Comparing this to the result described in the issue 408, the imbalance problem is greatly relieved. Test shows performance is also increased around 3%~5%, perhaps because the load is more evenly spreaded.
Test result: 16M vdisk size
Node 0:
0      417 GB  199 GB  218 GB   47%    /sheep/disk0
1      417 GB  198 GB  219 GB   47%    /sheep/disk1
2      417 GB  194 GB  223 GB   46%    /sheep/disk2
3      417 …

issue 408: Imbalanced storage utilization among multiple disks

---

sheepdog.spec.in

Fixed mismatch between Build-Requires and Install-Requires.

rpm: Fix BuildRequires mismatch

---

tests/script/exec_functional
tests/script/exec_operation
tests/script/exec_unit
tests/script/prepare_for_test

A small hack reduced the preparation time.
- Use multi-core option of `make` (`-j`)
- Use `--no-install-recommends` option of `apt-get`
- Manipulate depth option of `git clone`
---
Especially the preparation time can be shortened.
For example, the result in Travis CI. 
(If you are using many cpu cores machine, it will become more faster.)
| test             | befor   | after   |
|------------------|--------:|--------:|
| prepare_for_test | 217.24  | **159.37**  |
| exec_unit        | 48.33   | 41.37   |
| exec_operation   | 53.75   | 49.43   |
| exec_functional  | 971.23  | 961.66  |
| total            | 1290.55 | 1211.83 |
- Unit: seconds
- CPUs: 2

tests: speed up system prepare for test

---

dog/common.c
include/sockfd_cache.h
lib/sockfd_cache.c
sheep/sheep.c

Signed-off-by: Shien Xie <shien.xie@kaixiangtech.com>
The fix is to let sheepdog switching back to I/O NIC once I/O NIC is back online.
This is how the fix works:
A. We keep 2 sockfd_cache_fd arrays in each sockfd_cache_entry. The first array holds all fds for I/O NIC and the second holds all fds for Non-I/O NIC. When sheepdog starts, all fds in both arrays are -1 and immediately sheepdog pre-connect all fds. When a sheepdog worker thread (ie: gateway thread) needs a fd, it tries to get one from I/O NIC. If failed, it tries to get from the second array. This guarantees I/O NIC is always being chosen first.
B. A dedicated monitor thread is created to monitor all I/O NICs for each node(entry) in sockfd_cache.root. If the thread found an I/O NIC lost connection, it will close all fds in the …

New fix for issue 380 Correct recovery of I/O NIC

---

tests/functional/114

The `find` command can detect sparse files (`%S`)
Also, if just decide whether it is a sparse file or not, it's do not
need to consider the block size for SELinux anymore.
refs #409
---
This change makes test script will simple.
And although it is very little, but we can expect to speed up.
befor:
```
$ time sudo ./tests/functional/check 114
PLATFORM      -- Linux/x86_64 localhost 3.10.0-514.26.2.el7.x86_64
114  Test md plug and sparse object
Passed all 1 tests
real	0m7.624s
user	0m0.752s
sys	0m1.597s
```
after:
```
$ time sudo ./tests/functional/check 114
PLATFORM      -- Linux/x86_64 localhost 3.10.0-514.26.2.el7.x86_64
114  Test md plug and sparse object
Passed all 1 tests
real	0m6.644s
user	0m0.655s
sys	0m1.480s
```

tests: improve sparse file detection logic of functional 114

---

sbd/sbd.h

Add #include <linux/vmalloc.h> in sbd.h to be able to compile.
Issue and solution reported on github issue #201

Include missing header file in sbd.h

---

lib/util.c
sheep/gateway.c
sheep/request.c
sheep/store/plain_store.c
sheep/store/tree_store.c

We should use posix_memalign() instead of valloc().

lib, sheep: remove obsolete valloc() calls
